name: Build WASM

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. 拉取代码
      - uses: actions/checkout@v4

      # 2. 安装 Rust
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      # 3. 添加 wasm32 编译目标
      - name: Add wasm32 target
        run: rustup target add wasm32-unknown-unknown

      # 4. 安装 wasm-pack
      - name: Install wasm-pack
        run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh

      # 5. 编译为 WebAssembly
      - name: Build wasm (web target)
        run: wasm-pack build --target web --release

      # 6. 上传编译好的 wasm 包
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: wasm-pkg
          path: pkg
