name: Build WASM

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. 拉取代码
      - uses: actions/checkout@v4

      # 2. 安装 Rust（稳定版）
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          target: wasm32-unknown-unknown

      # 3. 安装 wasm-pack（Rust 官方推荐的打包工具）
      - name: Install wasm-pack
        run: cargo install wasm-pack

      # 4. 编译为 WebAssembly (生成 pkg/ 文件夹)
      - name: Build wasm (web target)
        run: wasm-pack build --target web --release

      # 5. 上传编译好的 wasm 包
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: wasm-pkg
          path: pkg
